[package]
name = "server"
version = "0.1.0"
authors = [ 
    "Sumner Evans <sumner.evans98@gmail.com>", 
    "Sam Sartor <me@samsartor.com>", 
    "Robbie Merillat <rdmerillat@mines.edu>" 
]

[dependencies]
common = {path = "../common"}